const express     = require('express');
const router      = express.Router();
const verifyToken = require('../middleware/auth');
const { getEmployees, getEmployeeById, createEmployee, updateEmployee, deleteEmployee } = require('../controllers/employeeController');
router.use(verifyToken);
router.get('/',       getEmployees);
router.get('/:id',    getEmployeeById);
router.post('/',      createEmployee);
router.put('/:id',    updateEmployee);
router.delete('/:id', deleteEmployee);
module.exports = router;
